# Generated by Django 2.1.2 on 2018-10-22 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppleAccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apple_account', models.CharField(max_length=50, unique=True)),
                ('email_pwd', models.CharField(max_length=50)),
                ('apple_pwd', models.CharField(max_length=50)),
                ('used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('game_name', models.CharField(blank=True, max_length=50, null=True)),
                ('vpn_name', models.CharField(blank=True, default='暂未设置', max_length=50, null=True)),
                ('account_type', models.CharField(choices=[('QY', '企业'), ('GR', '个人')], default='QY', max_length=50, verbose_name='帐号类型')),
                ('use_device', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用的设备')),
                ('upload_date', models.DateField(blank=True, null=True, verbose_name='上传日期')),
                ('parse_type', models.CharField(choices=[('None', '不做处理'), ('HX', '混淆1.0'), ('HX2', '混淆2.0'), ('JG', '加固'), ('SFJG', '第三方加固，混淆2.0'), ('SFCL', '第三方，原包')], default='None', max_length=50, verbose_name='项目处理类型')),
                ('small_game', models.BooleanField(default=False, verbose_name='是否为小游戏')),
                ('status', models.CharField(choices=[('NONE', '未使用'), ('DD', '等待审核'), ('ZZSH', '正在审核'), ('CW', '错误需要处理'), ('GB', '过包'), ('BDXX', '被动下线'), ('ZDXX', '主动下线')], default='NONE', max_length=200)),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='帐号创建时间')),
                ('user', models.ForeignKey(default='admin', on_delete=models.SET('admin'), to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='使用者')),
            ],
            options={
                'verbose_name': 'iOS帐号信息',
                'ordering': ['used'],
            },
        ),
    ]
