# Generated by Django 2.1.2 on 2018-10-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_accounteventmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounteventmodel',
            name='event_mes',
            field=models.CharField(max_length=1000, verbose_name='事件'),
        ),
    ]
