# Generated by Django 2.1.2 on 2018-10-22 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0003_auto_20181022_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounteventmodel',
            name='who_add',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='apple_event_who', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
