# Generated by Django 2.1.2 on 2018-10-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_accounteventmodel_who_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccountmodel',
            name='account_type',
            field=models.CharField(choices=[('QY', '企业'), ('GR', '个人'), ('QYQ', '企业签')], default='QY', max_length=50, verbose_name='帐号类型'),
        ),
        migrations.AlterField(
            model_name='appleaccountmodel',
            name='status',
            field=models.CharField(choices=[('NONE', '未使用'), ('DD', '等待审核'), ('ZZSH', '正在审核'), ('CW', '错误需要处理'), ('GB', '过包'), ('BDXX', '被动下线'), ('ZDXX', '主动下线')], default='NONE', max_length=200, verbose_name='帐号状态'),
        ),
    ]
