# Generated by Django 2.1.2 on 2018-10-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20181023_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccountmodel',
            name='status',
            field=models.CharField(choices=[('NONE', '未提交'), ('DD', '等待审核'), ('ZZSH', '正在审核'), ('CW', '错误需要处理'), ('GB', '过包'), ('BDXX', '被动下线'), ('ZDXX', '主动下线'), ('SFCL', '三方处理中'), ('WXTS', '不需要提审'), ('ZZZZ', '正在制作')], default='NONE', max_length=200, verbose_name='帐号状态'),
        ),
    ]
