# Generated by Django 2.1.2 on 2018-10-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20181023_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='appleaccountmodel',
            name='request_date',
            field=models.DateField(blank=True, null=True, verbose_name='申请使用时间'),
        ),
    ]
