# Generated by Django 2.1.2 on 2018-10-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_appleaccountmodel_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appleaccountmodel',
            name='parse_type',
            field=models.CharField(choices=[('None', '不做处理'), ('HX', '混淆1.0'), ('HX2', '混淆2.0'), ('JG', '加固'), ('SFJG', '第三方，混淆2.0'), ('SFCL', '第三方，原包')], default='None', max_length=50, verbose_name='项目处理类型'),
        ),
    ]
