# Generated by Django 2.1.2 on 2018-12-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20181027_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounteventmodel',
            name='event_date',
            field=models.DateField(auto_now=True, verbose_name='事件发生时间'),
        ),
        migrations.AlterField(
            model_name='appleaccountmodel',
            name='parse_type',
            field=models.CharField(choices=[('None', '不做处理'), ('HX', '混淆1.0'), ('HX2', '混淆2.0'), ('JG', '加固'), ('SFJG', '第三方，混淆2.0'), ('SFCL', '第三方，原包'), ('HX3', '混淆3.0')], default='None', max_length=50, verbose_name='项目处理类型'),
        ),
    ]
